[package]
name = "xunlei_bt_pool"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8"
md-5 = "0.10"
rsa = { version = "0.9", features = ["std"] }
hex = "0.4"
ureq = "2"
anyhow = "1"
bt_bencode = "0.8"
